name = "LiveDisplay"
uuid = "79a18240-257a-588a-8ffe-c432d0c87612"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
